
import os
import torch
# Placeholders pour whisper si non installé
try: 
    import whisper
    HAS_WHISPER = True
except: 
    HAS_WHISPER = False

INPUT_FOLDER = "Input"
OUTPUT_FOLDER = "Lyrics"

def generate_lyrics(progress_callback=None):
    if not os.path.exists(OUTPUT_FOLDER): os.makedirs(OUTPUT_FOLDER)
    files = [f for f in os.listdir(INPUT_FOLDER) if f.endswith(('.wav','.mp3'))]
    
    model = None
    if HAS_WHISPER:
        if progress_callback: progress_callback(10, "Chargement Whisper IA...")
        # Utilise 'base' pour la rapidité, 'medium' pour la précision
        model = whisper.load_model("base") 
    
    for i, f in enumerate(files):
        pct = int((i/len(files))*100)
        if progress_callback: progress_callback(pct, f"Transcribing {f}")
        
        txt_path = os.path.join(OUTPUT_FOLDER, f"{os.path.splitext(f)[0]}.lrc")
        
        if HAS_WHISPER and model:
            try:
                result = model.transcribe(os.path.join(INPUT_FOLDER, f))
                
                # Formatage LRC simple
                with open(txt_path, "w", encoding="utf-8") as lrc:
                    lrc.write("[00:00.00] Generated by Universal Audio Studio\n")
                    for seg in result["segments"]:
                        start = seg["start"]
                        mins = int(start // 60)
                        secs = int(start % 60)
                        ms = int((start % 1) * 100)
                        time_tag = f"[{mins:02}:{secs:02}.{ms:02}]"
                        lrc.write(f"{time_tag} {seg['text'].strip()}\n")
            except Exception as e:
                print(f"Whisper Error: {e}")
        else:
            # Fallback Dummy
            with open(txt_path, "w") as x: x.write("Whisper non installé ou erreur.\n")
